//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: wxMsOptionsw.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#ifndef _WXMS_CURL_WXMSOPTIONSDIALOG_WXMSOPTIONSW_BASE_CLASSES_H
#define _WXMS_CURL_WXMSOPTIONSDIALOG_WXMSOPTIONSW_BASE_CLASSES_H

#include <wx/settings.h>
#include <wx/xrc/xmlres.h>
#include <wx/xrc/xh_bmp.h>
#include <wx/dialog.h>
#include <wx/iconbndl.h>
#include <wx/artprov.h>
#include <wx/sizer.h>
#include <wx/notebook.h>
#include <wx/panel.h>
#include <wx/imaglist.h>
#include <wx/statbox.h>
#include <wx/checkbox.h>
#include <wx/button.h>
#include <wx/textctrl.h>
#include <wx/stattext.h>
#include <wx/spinctrl.h>
#include <wx/slider.h>
#include <wx/checklst.h>
#include <wx/clrpicker.h>
#include <wx/radiobox.h>
#include <wx/choice.h>
#include <wx/arrstr.h>
#if wxVERSION_NUMBER >= 2900
#include <wx/persist.h>
#include <wx/persist/toplevel.h>
#include <wx/persist/bookctrl.h>
#include <wx/persist/treebook.h>
#endif

#ifdef WXC_FROM_DIP
#undef WXC_FROM_DIP
#endif
#if wxVERSION_NUMBER >= 3100
#define WXC_FROM_DIP(x) wxWindow::FromDIP(x, NULL)
#else
#define WXC_FROM_DIP(x) x
#endif


class MyDialogOptionsBase : public wxDialog
{
protected:
    wxNotebook* m_notebookOptions;
    wxPanel* m_panelGeneral;
    wxCheckBox* m_checkBoxOptLaunchMailClient;
    wxButton* m_buttonPickMailClient;
    wxTextCtrl* m_textCtrlEmailClient;
    wxCheckBox* m_checkBoxOptCheckMailAtStart;
    wxStaticText* m_staticText20;
    wxCheckBox* m_checkBoxOptPlaySound;
    wxButton* m_buttonPickSound;
    wxCheckBox* m_checkBoxScheduleMailCheck;
    wxSpinCtrl* m_spinCtrlMailCheckInterval;
    wxStaticText* m_staticText36;
    wxCheckBox* m_checkBoxAutoUpdateCheck;
    wxSpinCtrl* m_spinCtrlMaxTopLines;
    wxCheckBox* m_checkBoxScheduleConnectCheck;
    wxSpinCtrl* m_spinCtrlMailServerConectCheckInterval;
    wxStaticText* m_staticText364;
    wxPanel* m_panelLog;
    wxCheckBox* m_cbOptLogToFile;
    wxCheckBox* m_cbOptLogUseDefaultPath;
    wxTextCtrl* m_tcOptLogFilesDestDir;
    wxButton* m_btnOptLogSelLogFilesDir;
    wxSlider* m_sliderOptLogVerbosity;
    wxStaticText* m_staticText1;
    wxSpinCtrl* m_spinCtrl1;
    wxStaticText* m_staticText2;
    wxCheckBox* m_checkBoxDailyLogFile;
    wxPanel* m_panelFilters;
    wxCheckListBox* m_checkListBoxFilter;
    wxButton* m_buttonFilterPrioityUp;
    wxButton* m_buttonFilterPriorityDown;
    wxTextCtrl* m_textCtrlFilterDescription;
    wxButton* m_buttonFilterAdd;
    wxButton* m_buttonFilterEdit;
    wxButton* m_buttonFilterDelete;
    wxColourPickerCtrl* m_colourPickerStatusDefColor;
    wxStdDialogButtonSizer* m_sdbSizer1;
    wxButton* m_button190;
    wxButton* m_button191;

protected:
    virtual void OnPickEmailClient(wxCommandEvent& event) { event.Skip(); }
    virtual void OnOptDlgLog_Log2FileClick(wxCommandEvent& event) { event.Skip(); }
    virtual void OnOptDlgLog_DefPathClick(wxCommandEvent& event) { event.Skip(); }
    virtual void OnOptDlgLog_SelLogFilePathClick(wxCommandEvent& event) { event.Skip(); }
    virtual void OnFilterListSelectionChanging(wxCommandEvent& event) { event.Skip(); }
    virtual void OnFilterUp(wxCommandEvent& event) { event.Skip(); }
    virtual void OnFilterDown(wxCommandEvent& event) { event.Skip(); }
    virtual void OnFilterAdd(wxCommandEvent& event) { event.Skip(); }
    virtual void OnFilterEdit(wxCommandEvent& event) { event.Skip(); }
    virtual void OnFilterDelete(wxCommandEvent& event) { event.Skip(); }

public:
    wxCheckBox* GetCheckBoxOptLaunchMailClient() { return m_checkBoxOptLaunchMailClient; }
    wxButton* GetButtonPickMailClient() { return m_buttonPickMailClient; }
    wxTextCtrl* GetTextCtrlEmailClient() { return m_textCtrlEmailClient; }
    wxCheckBox* GetCheckBoxOptCheckMailAtStart() { return m_checkBoxOptCheckMailAtStart; }
    wxStaticText* GetStaticText20() { return m_staticText20; }
    wxCheckBox* GetCheckBoxOptPlaySound() { return m_checkBoxOptPlaySound; }
    wxButton* GetButtonPickSound() { return m_buttonPickSound; }
    wxCheckBox* GetCheckBoxScheduleMailCheck() { return m_checkBoxScheduleMailCheck; }
    wxSpinCtrl* GetSpinCtrlMailCheckInterval() { return m_spinCtrlMailCheckInterval; }
    wxStaticText* GetStaticText36() { return m_staticText36; }
    wxCheckBox* GetCheckBoxAutoUpdateCheck() { return m_checkBoxAutoUpdateCheck; }
    wxSpinCtrl* GetSpinCtrlMaxTopLines() { return m_spinCtrlMaxTopLines; }
    wxCheckBox* GetCheckBoxScheduleConnectCheck() { return m_checkBoxScheduleConnectCheck; }
    wxSpinCtrl* GetSpinCtrlMailServerConectCheckInterval() { return m_spinCtrlMailServerConectCheckInterval; }
    wxStaticText* GetStaticText364() { return m_staticText364; }
    wxPanel* GetPanelGeneral() { return m_panelGeneral; }
    wxCheckBox* GetCbOptLogToFile() { return m_cbOptLogToFile; }
    wxCheckBox* GetCbOptLogUseDefaultPath() { return m_cbOptLogUseDefaultPath; }
    wxTextCtrl* GetTcOptLogFilesDestDir() { return m_tcOptLogFilesDestDir; }
    wxButton* GetBtnOptLogSelLogFilesDir() { return m_btnOptLogSelLogFilesDir; }
    wxSlider* GetSliderOptLogVerbosity() { return m_sliderOptLogVerbosity; }
    wxStaticText* GetStaticText1() { return m_staticText1; }
    wxSpinCtrl* GetSpinCtrl1() { return m_spinCtrl1; }
    wxStaticText* GetStaticText2() { return m_staticText2; }
    wxCheckBox* GetCheckBoxDailyLogFile() { return m_checkBoxDailyLogFile; }
    wxPanel* GetPanelLog() { return m_panelLog; }
    wxCheckListBox* GetCheckListBoxFilter() { return m_checkListBoxFilter; }
    wxButton* GetButtonFilterPrioityUp() { return m_buttonFilterPrioityUp; }
    wxButton* GetButtonFilterPriorityDown() { return m_buttonFilterPriorityDown; }
    wxTextCtrl* GetTextCtrlFilterDescription() { return m_textCtrlFilterDescription; }
    wxButton* GetButtonFilterAdd() { return m_buttonFilterAdd; }
    wxButton* GetButtonFilterEdit() { return m_buttonFilterEdit; }
    wxButton* GetButtonFilterDelete() { return m_buttonFilterDelete; }
    wxColourPickerCtrl* GetColourPickerStatusDefColor() { return m_colourPickerStatusDefColor; }
    wxPanel* GetPanelFilters() { return m_panelFilters; }
    wxNotebook* GetNotebookOptions() { return m_notebookOptions; }
    MyDialogOptionsBase(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = _("Options"), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(-1,-1), long style = wxDEFAULT_DIALOG_STYLE|wxRESIZE_BORDER);
    virtual ~MyDialogOptionsBase();
};


class MyDialogFilterEditBase : public wxDialog
{
protected:
    wxPanel* m_panel199;
    wxStaticText* m_staticTextFilterName;
    wxTextCtrl* m_textCtrlFilterEdit_FilterName;
    wxStaticText* m_staticTextFilterStatusText;
    wxTextCtrl* m_textCtrlFilterEdit_FilterStatus;
    wxColourPickerCtrl* m_colourPickerFilterColor;
    wxStaticText* m_staticTextPriority;
    wxCheckBox* m_checkBoxFilterPriority;
    wxStaticText* m_staticTextFilterAction;
    wxCheckBox* m_checkBoxActionLegit;
    wxCheckBox* m_checkBoxActionBlacklist;
    wxCheckBox* m_checkBoxActionMarkDel;
    wxCheckBox* m_checkBoxActionMarkBounce;
    wxStaticText* m_staticText125;
    wxRadioBox* m_radioBoxFilterAndOr;
    wxChoice* m_choiceRuleSourceString;
    wxChoice* m_choiceRuleCriteria;
    wxTextCtrl* m_textCtrlRuleMsgText;
    wxButton* m_buttonFilterMoreRules;
    wxButton* m_buttonFilterFewerRules;
    wxStdDialogButtonSizer* m_stdBtnSizer127;
    wxButton* m_buttonFilterOK;
    wxButton* m_buttonFilterCancel;

protected:
    virtual void OnColourChanged(wxColourPickerEvent& event) { event.Skip(); }
    virtual void OnFilterEditIsLegitimate(wxCommandEvent& event) { event.Skip(); }

public:
    wxStaticText* GetStaticTextFilterName() { return m_staticTextFilterName; }
    wxTextCtrl* GetTextCtrlFilterEdit_FilterName() { return m_textCtrlFilterEdit_FilterName; }
    wxStaticText* GetStaticTextFilterStatusText() { return m_staticTextFilterStatusText; }
    wxTextCtrl* GetTextCtrlFilterEdit_FilterStatus() { return m_textCtrlFilterEdit_FilterStatus; }
    wxColourPickerCtrl* GetColourPickerFilterColor() { return m_colourPickerFilterColor; }
    wxStaticText* GetStaticTextPriority() { return m_staticTextPriority; }
    wxCheckBox* GetCheckBoxFilterPriority() { return m_checkBoxFilterPriority; }
    wxStaticText* GetStaticTextFilterAction() { return m_staticTextFilterAction; }
    wxCheckBox* GetCheckBoxActionLegit() { return m_checkBoxActionLegit; }
    wxCheckBox* GetCheckBoxActionBlacklist() { return m_checkBoxActionBlacklist; }
    wxCheckBox* GetCheckBoxActionMarkDel() { return m_checkBoxActionMarkDel; }
    wxCheckBox* GetCheckBoxActionMarkBounce() { return m_checkBoxActionMarkBounce; }
    wxStaticText* GetStaticText125() { return m_staticText125; }
    wxRadioBox* GetRadioBoxFilterAndOr() { return m_radioBoxFilterAndOr; }
    wxChoice* GetChoiceRuleSourceString() { return m_choiceRuleSourceString; }
    wxChoice* GetChoiceRuleCriteria() { return m_choiceRuleCriteria; }
    wxTextCtrl* GetTextCtrlRuleMsgText() { return m_textCtrlRuleMsgText; }
    wxButton* GetButtonFilterMoreRules() { return m_buttonFilterMoreRules; }
    wxButton* GetButtonFilterFewerRules() { return m_buttonFilterFewerRules; }
    wxPanel* GetPanel199() { return m_panel199; }
    MyDialogFilterEditBase(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = _("Edit Filter"), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(-1,-1), long style = wxDEFAULT_DIALOG_STYLE|wxRESIZE_BORDER);
    virtual ~MyDialogFilterEditBase();
};

#endif
