//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: wxMsUpdateCheck.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#ifndef WXMS_WXMSUPDATECHECK_WXMSUPDATECHECK_BASE_CLASSES_H
#define WXMS_WXMSUPDATECHECK_WXMSUPDATECHECK_BASE_CLASSES_H

#include <wx/settings.h>
#include <wx/xrc/xmlres.h>
#include <wx/xrc/xh_bmp.h>
#include <wx/dialog.h>
#include <wx/iconbndl.h>
#include <wx/artprov.h>
#include <wx/sizer.h>
#include <wx/stattext.h>
#include <wx/hyperlink.h>
#include <wx/button.h>
#if wxVERSION_NUMBER >= 2900
#include <wx/persist.h>
#include <wx/persist/toplevel.h>
#include <wx/persist/bookctrl.h>
#include <wx/persist/treebook.h>
#endif

class MyUpdateCheckBase : public wxDialog
{
protected:
    wxStaticText* m_staticText25;
    wxStaticText* m_staticTextLatest;
    wxStaticText* m_staticTextVisit;
    wxHyperlinkCtrl* m_hyperLinkUpdateURL;
    wxStaticText* m_staticTextNote1;
    wxStaticText* m_staticTextNote2;
    wxStdDialogButtonSizer* m_stdBtnSizer21;
    wxButton* m_button23;

protected:

public:
    wxStaticText* GetStaticText25() { return m_staticText25; }
    wxStaticText* GetStaticTextLatest() { return m_staticTextLatest; }
    wxStaticText* GetStaticTextVisit() { return m_staticTextVisit; }
    wxHyperlinkCtrl* GetHyperLinkUpdateURL() { return m_hyperLinkUpdateURL; }
    wxStaticText* GetStaticTextNote1() { return m_staticTextNote1; }
    wxStaticText* GetStaticTextNote2() { return m_staticTextNote2; }
    MyUpdateCheckBase(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = _("Check for Updates"), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(500,300), long style = wxDEFAULT_DIALOG_STYLE);
    virtual ~MyUpdateCheckBase();
};

#endif
