//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: wxMsAboutDlg.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#ifndef _WXMS_2015_WXMSABOUT_WXMSABOUTDLG_BASE_CLASSES_H
#define _WXMS_2015_WXMSABOUT_WXMSABOUTDLG_BASE_CLASSES_H

#include <wx/settings.h>
#include <wx/xrc/xmlres.h>
#include <wx/xrc/xh_bmp.h>
#include <wx/dialog.h>
#include <wx/iconbndl.h>
#include <wx/artprov.h>
#include <wx/sizer.h>
#include <wx/statbmp.h>
#include <wx/stattext.h>
#include <wx/notebook.h>
#include <wx/panel.h>
#include <wx/imaglist.h>
#include <wx/hyperlink.h>
#include <wx/statbox.h>
#include <wx/button.h>
#if wxVERSION_NUMBER >= 2900
#include <wx/persist.h>
#include <wx/persist/toplevel.h>
#include <wx/persist/bookctrl.h>
#include <wx/persist/treebook.h>
#endif

#ifdef WXC_FROM_DIP
#undef WXC_FROM_DIP
#endif
#if wxVERSION_NUMBER >= 3100
#define WXC_FROM_DIP(x) wxWindow::FromDIP(x, NULL)
#else
#define WXC_FROM_DIP(x) x
#endif


class wxMsAboutDlgBase : public wxDialog
{
public:
    enum {
        ID_HYPERLINKCTRL_WXWIDGETS = 10001,
        ID_NOTEBOOK = 10002,
        ID_PANEL_ARTISTS = 10003,
        ID_PANEL_CREDITS = 10004,
        ID_PANEL_DEVELOPERS = 10005,
    };
protected:
    wxStaticBitmap* m_staticBitmapAbout;
    wxStaticText* m_staticTextProgName;
    wxStaticText* m_staticTextAppNameLine2;
    wxStaticText* m_staticTextCopyright;
    wxStaticText* m_staticTextVersion;
    wxNotebook* m_notebookData;
    wxPanel* m_panelDevelopers;
    wxStaticText* m_staticText25;
    wxPanel* m_panelArtists;
    wxStaticText* m_staticTextArtists;
    wxPanel* m_panelCredits;
    wxStaticText* m_staticText37;
    wxHyperlinkCtrl* m_hyperLinkWxWidgets;
    wxHyperlinkCtrl* m_hyperLinkLibCurl;
    wxHyperlinkCtrl* m_hyperLinkMimeticLib;
    wxPanel* m_panelLicense;
    wxStaticText* m_staticText131;
    wxStaticText* m_staticText127;
    wxStaticText* m_staticText129;
    wxPanel* m_panelSystemInfo;
    wxStaticText* m_staticTextwxWidgetsVersion;
    wxStaticText* m_staticTextLibcurlVersion;
    wxStaticText* m_staticTextMimeticVersion;
    wxStaticText* m_staticTextCompiler;
    wxStaticText* m_staticTextOS;
    wxStaticText* m_staticTextOsPort;
    wxStaticText* m_staticTextConfigDir;
    wxButton* m_buttonOK;

protected:

public:
    wxStaticBitmap* GetStaticBitmapAbout() { return m_staticBitmapAbout; }
    wxStaticText* GetStaticTextProgName() { return m_staticTextProgName; }
    wxStaticText* GetStaticTextAppNameLine2() { return m_staticTextAppNameLine2; }
    wxStaticText* GetStaticTextCopyright() { return m_staticTextCopyright; }
    wxStaticText* GetStaticTextVersion() { return m_staticTextVersion; }
    wxStaticText* GetStaticText25() { return m_staticText25; }
    wxPanel* GetPanelDevelopers() { return m_panelDevelopers; }
    wxStaticText* GetStaticTextArtists() { return m_staticTextArtists; }
    wxPanel* GetPanelArtists() { return m_panelArtists; }
    wxStaticText* GetStaticText37() { return m_staticText37; }
    wxHyperlinkCtrl* GetHyperLinkWxWidgets() { return m_hyperLinkWxWidgets; }
    wxHyperlinkCtrl* GetHyperLinkLibCurl() { return m_hyperLinkLibCurl; }
    wxHyperlinkCtrl* GetHyperLinkMimeticLib() { return m_hyperLinkMimeticLib; }
    wxPanel* GetPanelCredits() { return m_panelCredits; }
    wxStaticText* GetStaticText131() { return m_staticText131; }
    wxStaticText* GetStaticText127() { return m_staticText127; }
    wxStaticText* GetStaticText129() { return m_staticText129; }
    wxPanel* GetPanelLicense() { return m_panelLicense; }
    wxStaticText* GetStaticTextwxWidgetsVersion() { return m_staticTextwxWidgetsVersion; }
    wxStaticText* GetStaticTextLibcurlVersion() { return m_staticTextLibcurlVersion; }
    wxStaticText* GetStaticTextMimeticVersion() { return m_staticTextMimeticVersion; }
    wxStaticText* GetStaticTextCompiler() { return m_staticTextCompiler; }
    wxStaticText* GetStaticTextOS() { return m_staticTextOS; }
    wxStaticText* GetStaticTextOsPort() { return m_staticTextOsPort; }
    wxStaticText* GetStaticTextConfigDir() { return m_staticTextConfigDir; }
    wxPanel* GetPanelSystemInfo() { return m_panelSystemInfo; }
    wxNotebook* GetNotebookData() { return m_notebookData; }
    wxButton* GetButtonOK() { return m_buttonOK; }
    wxMsAboutDlgBase(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = _("About wxMS"), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(-1,-1), long style = wxDEFAULT_DIALOG_STYLE|wxCAPTION|wxRESIZE_BORDER|wxCLOSE_BOX);
    virtual ~wxMsAboutDlgBase();
};

#endif
